version: '3.8'
services:
  go:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: 'tail -f /dev/null'
    volumes:
      - ./:/go/app
      - exclude:/go/app/node_modules/
    environment:
      DEPLOY_STAGE: ${DEPLOY_STAGE}
      TARGET_USER_POOL_ID: ${TARGET_USER_POOL_ID}
      TRIGGER_USER_POOL_NAME: ${TRIGGER_USER_POOL_NAME}
      REGION: ${REGION}
      KIMONO_APP_FRONTEND_URL: ${KIMONO_APP_FRONTEND_URL}
volumes:
  exclude:
    driver: 'local'
